from openai import OpenAI
import os
from dotenv import load_dotenv
import json


def get_horoscope(sign):
    return f"{sign}: Next Tuesday you will befriend a baby otter."

def main():

    load_dotenv()

    # 1. Define a list of callable tools for the model
    tools = [
        {
            "type": "function",
            "name": "get_horoscope",
            "description": "Get today's horoscope for an astrological sign.",
            "parameters": {
                "type": "object",
                "properties": {
                    "sign": {
                        "type": "string",
                        "description": "An astrological sign like Taurus or Aquarius",
                    },
                },
                "required": ["sign"],
            },
        },
    ]

    # Create a running input list we will add to over time
    input_list = [{"role": "user", "content": "What is my horoscope? I am an Aquarius."}]
        
    api_key = "GROQ_API_KEY"
    base_url = "GROQ_BASE_URL"
    model = "GROQ_MODEL"
    
    client = OpenAI(
        api_key=os.getenv(api_key),
        base_url=os.getenv(base_url),
        timeout=30.0,
        max_retries=0
    )

    # 2. Prompt the model with tools defined
    response = client.responses.parse(
        model = os.getenv(model),
        input = input_list,
        tools = tools,
    )

    # Save function call outputs for subsequent requests
    input_list += response.output

    for item in response.output:
        if item.type == "function_call":
            if item.name == "get_horoscope":

                # 3. Execute the function logic for get_horoscope
                sign = json.loads(item.arguments)["sign"]
                horoscope = get_horoscope(sign)

                # 4. Provide function call results to the model
                input_list.append(
                    {
                        "type" : "function_call_output",
                        "call_id" : item.call_id,
                        "output" : horoscope
                    }
                )

    print("Final input:")
    print(input_list)

    response = client.responses.parse(
        model = os.getenv(model),
        input = input_list,
        tools = tools,
        instructions = "Respond only with a horoscope generated by a tool."
    )

    # 5. The model should be able to give a response!
    print("Final output:")
    print(response.model_dump_json(indent=2))
    print("\n" + response.output_text)

main()

        

